config/routes.rb
Rails.application.routes.draw do
  resources :fighter_searches, param: :uuid, only: [ :create, :show ]
  resources :battles, param: :replay_id, only: :show
  resources :fighters, only: [], constraints: { id: Patterns::SHORT_ID_REGEXP } do
    get "search" => "fighter_searches#new", on: :collection
    get "/" => redirect("/fighters/search"), on: :collection
    get "/" => redirect("/fighters/%{id}/matches"), on: :member

    scope module: :fighters do
      resource :synchronization, only: [ :create, :show ]
      resource :matches, only: :show
      resource :daily_results_chart, only: :show
      resource :rivals, only: :show
      resource :matchup_chart, only: :show
      resource :ranked_history, only: :show
    end

    match "/*", to: redirect { |params, _req| "/fighters/#{params[:fighter_id]}" }, via: :get
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  get "/about" => "pages#about"
  get "/fair_use_agreement" => "pages#fair_use_agreement"

  # Defines the root path route ("/")
  root "pages#index"
end

app/models/match.rb
class Match < ApplicationRecord
  include MasterRatingCalculation

  composed_of_enum :home_rounds, :home_round_ids, class_name: "Round", array: true
  composed_of_enum :home_character, :home_character_id, class_name: "Character"
  composed_of_enum :home_playing_character, :home_playing_character_id, class_name: "Character"
  composed_of_enum :home_input_type, :home_input_type_id, class_name: "InputType"
  composed_of_enum :away_rounds, :away_round_ids, class_name: "Round", array: true
  composed_of_enum :away_character, :away_character_id, class_name: "Character"
  composed_of_enum :away_playing_character, :away_playing_character_id, class_name: "Character"
  composed_of_enum :away_input_type, :away_input_type_id, class_name: "InputType"
  composed_of_enum :battle_type, :battle_type_id
  composed_of_enum :result, :result

  scope :ranked, -> { where(battle_type: BattleType::RANKED) }

  def ranked? = battle_type == BattleType::RANKED

  def self.aggregate_results
    ResultAggregation.new(all)
  end

  def self.daily_results
    group_by_day(:played_at)
      .then { it.select("#{it.group_values.last} date") }
      .order("date")
      .aggregate_results
      .to_h { |data, score| [ data["date"], score ] }
  end

  def readonly?
    true
  end
end

app/models/match/master_rating_calculation.rb
module Match::MasterRatingCalculation
  extend ActiveSupport::Concern

  def mr_match?
    ranked? && home_mr.positive? && away_mr.positive?
  end

  def home_mr_variation
    MasterRatingCalculator.new(home_mr:, away_mr:, result:).calculate if mr_match?
  end
end

app/models/match/result_aggregation.rb
class Match::ResultAggregation
  include Enumerable

  def initialize(relation)
    @relation = relation.select(
      "COUNT(result = #{Result::WIN} OR NULL) AS wins",
      "COUNT(result = #{Result::LOSS} OR NULL) AS losses",
      "COUNT(result = #{Result::DRAW} OR NULL) AS draws",
      "SUM(result) AS diff",
      "COUNT(1) AS total"
    )
  end

  def each(&)
    ApplicationRecord.with_connection { |conn| conn.select_all(@relation) }.map do |row|
      score_data = row.extract!("wins", "losses", "draws", "diff", "total")
      score = Score.new(**score_data.except("diff", "total"))
      [ row, score ]
    end.each(&)
  end

  def total
    ApplicationRecord.with_connection { |conn| conn.select_one(@relation) }.then do |row|
      Score.new(**row.except("diff", "total"))
    end
  end
end

app/controllers/fighters/matches_controller.rb
class Fighters::MatchesController < ApplicationController
  include FighterScoped
  include SetMatchesFilter
  ads_eligible
  fresh_when_synchronized_at_changed
  layout "fighter"

  def show
    @pagy, @matches = pagy(:offset, @matches_filter.filter(@fighter.matches).order(played_at: :desc))
  end
end

app/views/matches/_daily_results_chart.html.erb
<%= render DailyResultsChart.new(matches.daily_results) %>

app/views/matches/_matches_table.html.erb
<table class="table table-striped text-center text-nowrap">
  <thead>
    <th colspan="3"><%= Match.human_attribute_name :home_challenger %></th>
    <th><%= Match.human_attribute_name :result %></th>
    <th colspan="3"><%= Match.human_attribute_name :away_challenger %></th>
    <th><%= Match.human_attribute_name :battle_type %></th>
    <th><%= Match.human_attribute_name :replay_id %></th>
    <th><%= Match.human_attribute_name :played_at %></th>
  </thead>
  <tbody>
    <% matches.each do |match| %>
      <tr>
        <td><%= link_to_fighter match.home_name, match.home_fighter_id %></td>
        <td><%= human_enum_name match.home_character %></td>
        <td><%= human_enum_name match.home_input_type %></td>
        <td><%= result_badge match.result %></td>
        <td><%= link_to_fighter match.away_name, match.away_fighter_id %></td>
        <td><%= human_enum_name match.away_character %></td>
        <td><%= human_enum_name match.away_input_type %></td>
        <td><%= human_enum_name match.battle_type %></td>
        <td><%= link_to_modal match.replay_id, battle_path(match.replay_id) %></td>
        <td><%= local_time_ago match.played_at %></td>
      </tr>
    <% end %>
  </tbody>
</table>